#!/bin/sh                                                                                       

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

PID="org.webosinternals.upstartmgr"

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/etc/event.d/${PID} /etc/event.d/${PID}

# Install the service binary
if [ "$IPKG_OFFLINE_ROOT" != "/var" ] ; then
  rm -f /var/usr/sbin/${PID}
  mkdir -p /var/usr/sbin
  cp $IPKG_OFFLINE_ROOT/usr/sbin/${PID} /var/usr/sbin/${PID}
fi

# Install the dbus service
rm -f /usr/share/dbus-1/system-services/${PID}.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/${PID}.service /usr/share/dbus-1/system-services/${PID}.service

# Start the service
/sbin/start ${PID}

exit 0
